# Exercise 190524

In [3]:
import numpy as np

### Bolean indexing

In [12]:
a = np.arange(1,4)
a


array([1, 2, 3])

In [14]:
a[[True, False, True]]

array([1, 3])

In [16]:
# task: get all even elements from array
a=np.arange(1,30)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [25]:
mask = a%2 == 0
evens = a[mask]
evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [24]:
b = np.arange(1,10)
print(f'b: {b}')
print(f'b+7:{b+7}')

b: [1 2 3 4 5 6 7 8 9]
b+7:[ 8  9 10 11 12 13 14 15 16]


Masking example 2 : group 'scores' by category
Let's have an array of 'scores', and for each score we'll have to assign a category from a predefined list. The goal is to group scores (first column) under 'bad' and 'good' categories, based on the second column.

In [49]:
# Define the scores array
scores = np.array([
    [4, 1],
    [2, 0],
    [3, 0],
    [5, 1],
    [6, 1]
])
categories = ['good', 'bad']
good_scores = scores[:,1]==1
bad_scores = scores[:,1]==0
good = scores[good_scores]
bad = scores[bad_scores]
print(f'good: \n {good}')
print(f'bad: \n{bad}')

good: 
 [[4 1]
 [5 1]
 [6 1]]
bad: 
[[2 0]
 [3 0]]
